import Head from "next/head";
import About from "../components/About";
import Contact from "../components/Contact";
import Navbar from "../components/Navbar";
import Projects from "../components/Projects";
import Showcase from "../components/Showcase";
import TechStack from "../components/TechStack";

export default function Home() {
    return (
        <div className="bg-gray-900">
            <Head>
                <title>Vincent Gitonga</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
                <link
                    href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,200;0,300;0,400;1,100&display=swap"
                    rel="stylesheet"
                ></link>
            </Head>
            <Navbar />
            <Showcase />
            <About />
            <TechStack />
            <Projects />
            <Contact />
        </div>
    );
}
